---

name: Build this Docker image
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: master
  # schedule:
  #   - cron: '11 23 * * 0'

env:
  IMAGE_NAME:     "devopsansiblede/ldap"
  TAG_PRODUCTION: "latest"
  TAG_TESTING:    "testing"

jobs:
  test:
    name:    Test the image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and keep testing image locally
        id: build_docker_test
        uses: docker/build-push-action@v3
        with:
          context: .
          load:    true
          tags:    "${{ env.IMAGE_NAME }}:${{ env.TAG_TESTING }}"
          build-args: |
            BUILD_ARG_TESTING=yes

      - name: Running the testing image and waiting for 60 seconds to ensure the configuration took place
        id:   image_test
        run: |
          docker run --name ldap_test -t --rm \
                 -e LEGO_TEST_CONFIG='${{ secrets.LEGO_TEST_CONFIG }}' \
                 ${{ env.IMAGE_NAME }}:${{ env.TAG_TESTING }} test

  release:
    name:    Build image
    runs-on: ubuntu-latest
    needs:   test

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        id: docker_push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push:      true
          tags:      "${{ env.IMAGE_NAME }}:${{ env.TAG_PRODUCTION }}"

      - name: Image digest
        run: echo ${{ steps.docker_push.outputs.digest }}

      - name: Last Build
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" README.md

      - name: Commit last built comment
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Last built
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me

...
